## __Common Mathematical and Statistical Function in Numpy__
## Step 1: Import the NumPy Library and Create an Array


In [ ]:
import numpy as np

Create a 2D array:

In [ ]:
arr = np.array([[4,3,2],[10,1,0],[5,8,24]])

Display the array using its variable name:

In [ ]:
arr

array([[ 4,  3,  2],
       [10,  1,  0],
       [ 5,  8, 24]])

## Step 2: Minimum and Maximum Values in an Array
- Use the `np.amin()` function to find the minimum value in an array
- Use the `np.amax()` function to find the maximum value in an array

Now, let's determine the minimum value in the array:

In [ ]:
np.amin(arr)

0

Now, calculate the minimum values in the array along the vertical axis:

In [ ]:
np.amin(arr,axis=0)

array([4, 1, 0])

**Observation:**
- `axis=0` gives you the minimum values in along the vertical axis as shown above.

Then, calculate the minimum values in the array along the horizontal axis:

In [ ]:
np.amin(arr,axis=1)

array([2, 0, 5])

**Observation:**
- `axis=1` gives you the minimum values along the horizontal axis as shown above.

Now, calculate the maximum value of the array using `np.max()`

In [ ]:
np.max(arr)

24

Now, let's calculate the maximum values of the array along the vertical and horizontal axes using `np.amax()` with axis parameter:
- The same pattern of choosing values in horizonatal and vertical axes has been followed.

In [ ]:
np.amax(arr,axis=0)

array([10,  8, 24])

In [ ]:
np.amax(arr,axis=1)

array([ 4, 10, 24])

## Step 3: Compute Median, Mean, Standard Deviation and Variance in the Array

Here, we will start by calculating the median of the NumPy array.

In [ ]:
np.median(arr)

4.0

Then, calculate the mean of the NumPy array:

In [ ]:
np.mean(arr)

-2.7925

Then, calculate the standard deviation of the NumPy array:

In [ ]:
np.std(arr)

6.944222218666553

Then, calculate the variance of the NumPy array:

In [ ]:
np.var(arr)

48.22222222222222

## Step 4: Calculate Percentiles
- The `np.percentile()` function is used to compute the nth percentile of the array elements.

- The nth percentile value should be in between 0 and 100.

Find the value under the 50th percentile of the NumPy array.



In [ ]:
np.percentile(arr,50)

4.0

## Step 5: Trigonometric Functions

Now, we will learn to execute the trigonometric functions.

- Compute sine, cosine and tangent of the NumPy array using `np.sin()`, `np.cos()`, and `np.tan()` respectively


Let's create an array of degree values using `np.array()`:

In [ ]:
deg = np.array([0,30,45,60,90])

Then, convert the degrees to radians by multiplying the values with pi/180 and then find the sine value using the sine function:

In [ ]:
np.sin(deg*np.pi/180)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

Then, convert the degrees to radians by multiplying the values with pi/180 and then find the cosine value using the cosine function:

In [ ]:
np.cos(deg*np.pi/180)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

Now, convert the degrees to radians by multiplying the values with pi/180 and then find the tangent value using the tangent function:

In [ ]:
np.tan(deg*np.pi/180)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

You can also work with inverse trigonometric functions, such as:
- arcsin
- arccos
- arctan


## Step 6: Floor and Ceil Functions

Here, we will calculate the floor and ceil values.

1. Floor: Round down
2. Ceil: Round up


Let's create a NumPy array:

In [ ]:
arr = np.array([0.1,0.8,-2.2,-9.87])

Then, calculate the floor values of the NumPy array:

In [ ]:
np.floor(arr)

array([  0.,   0.,  -3., -10.])

Finally, let's calculate the ceil values of the NumPy array:

In [ ]:
np.ceil(arr)

array([ 1.,  1., -2., -9.])