## Numpy - Numerical Python

- It allows working with `multi-dimensional arrays` or `nd arrays`

- It also allows `broadcasting and vectorization` which helps speed up calculations by using multiple cores.

In [1]:
!pip install numpy
import numpy as np # as np => renaming numpy in the current namespace as np, so I don't have type

## Creating an Array of Zeros

```python
np.zeros("Shape")
```

In [2]:
# Instantiates numpy array, of size 5 where everythign inside is a 0 

# np.zeros : function takes in a integer parameter and creates a np.array of size int 
## With just 0s
test = np.zeros(5)

In [3]:
# 1 dimensional
test 

array([0., 0., 0., 0., 0.])

In [4]:
# to make 2 -D array, can pass in a tuple, or list


np_dimension_tuple = (3, 4) # rows, cols
test_2d = np.zeros(np_dimension_tuple)

In [5]:
test_2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
# np.zeros does type checking on the input parameter
np.zeros("hello world")

TypeError: 'str' object cannot be interpreted as an integer

## Numpy Terminology

- Each `Dimension` of the array is called an `Axis`.

- ### first_dimension rank == 2, second_dimension_rank == 3
- ###


- Number of Axes of the array is called the `Rank`.  

- The shape of the array is given by the `List of ranks`.  

- The no of elements in the array is given by the `Product of the ranks`.

In [13]:

zeros = np.zeros((2, 2)) # dimension


print(f"No of Dimensions: {zeros.ndim}")
print(f"Shape: {zeros.shape}")
print(f"Size: {zeros.size}") # total number of cells in the array

No of Dimensions: 2
Shape: (2, 2)
Size: 4


In [14]:
zeros

array([[0., 0.],
       [0., 0.]])

In [9]:
another_zeros = np.zeros((1, 10, 4))

print(f"No of Dimensions: {another_zeros.ndim}")
print(f"Shape: {another_zeros.shape}")
print(f"Size: {another_zeros.size}")

No of Dimensions: 3
Shape: (1, 10, 4)
Size: 40


## Creating Nd Arrays

In [15]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## Creating Different Types of Arrays

- np.ones(`shape`)

In [16]:
print("Array of Ones: ")
print(np.ones((2, 3)))

Array of Ones: 
[[1. 1. 1.]
 [1. 1. 1.]]


Create an array with a specific number that isn't 0, 1, or None
- np.full(`Shape`, `Custom Number`)

In [28]:
print("Array of any custom number: ")

# custom number respects the type passed
test_passed_type = np.full((2, 3), 10)
print(test_passed_type)

Array of any custom number: 
[[10 10 10]
 [10 10 10]]


In [29]:
type(test_passed_type[0][0])

numpy.int64

- np.empty(`Shape`)

In [19]:
print("Array of empty values reflecting the values of the memory address")
print(np.empty((3, 4)))

Array of empty values reflecting the values of the memory address
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
zeros = np.zeros((1, 1))
empty = np.empty((1, 1))

In [25]:
zeros is empty

False

In [26]:
# np.empty and np.zeros gives the same values (0 float)
zeros == empty

array([[ True]])

In [23]:
# This is the numpy none object.
## Different from python None

## Empty cells in a csv read by pandas will be interpreted as np.nan
np.nan == None

False

In [30]:
test_nan = np.nan

In [33]:
# how to test that nan is nan!  
print(np.isnan(test_nan))

## This is weird
print(test_nan == np.nan)
print(test_nan is np.nan)

True
False
True


## Converting a python list to an array

- np.array(`List`, `dtype`)

In [43]:
oned_list = [1, 2, 3]

# Passing in the list directly into np.array()
## expectation: numpy array with 1 dimension, 1 row and 3 columns, with values 1,2, 3
test = np.array(oned_list)
print(test)
print(test.shape)

[1 2 3]
(3,)


In [38]:
# can also take numpy array as input
np.array(np.array(oned_list))

array([1, 2, 3])

In [40]:
twod_list = [[],[],[]] # 2 d empty list of lists [3, 0]

np.array(twod_list)


array([], shape=(3, 0), dtype=float64)

In [42]:
ls = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]
test = np.array(ls)
print(np.array(ls))
print(test.shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
(5, 2)


In [44]:
# return an array to a python list
test.tolist()

[1, 2, 3]

In [51]:
# zero dimension arrays
zero_dim_array = np.array(1)
print(zero_dim_array)
print(zero_dim_array.shape)

1
()


# Calling a cell in NP Arrays

In [53]:
oned_test = np.array([0, 1, 2, 3])

# call is just like a list: oned_test[index_number]
# print 1
oned_test[0]

0

In [55]:
ls = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]
twod_test = np.array(ls)

# twod_test[row_index][col_index]  => This syntax works on lists of lists in Python
# twod_test[row_index, col_index]
print(twod_test[0][0])
print(twod_test[0,0])

1
1


## Numpy Arrays

![](https://i.stack.imgur.com/NWTQH.png)

### Python lists are not created for scientific computing. They can store data and provide a lot usability, but when it comes to math and matrix we have Numpy arrays

1. Python lists are fundamentally created to be data stores that mirror major function of arrays and fix major developer pain of arrays in other languages
   - pain: resizing the array over the course of the program; mixed data object types in that array.
3. Numpy arrays are meant to express mathmatical matrix behavior.
4. Python list behavior like addition is NOT the same as matrix addition behavior. 
5. There are simple mathmatical tasks that are available to matrices (and also numpy arrays) that ARE NOT available to python lists, like subtraction, multiplication, division.

In [57]:
# let's see how python lists behave
a = [1,2,3]
b = [4,5,6]

# Example of python list addition.
a + b

[1, 2, 3, 4, 5, 6]

In [58]:
a_np = np.array(a)
b_np = np.array(b)

# numpy addition is replicating matrix addition!!  Not extending size of array
a_np + b_np

array([5, 7, 9])

In [59]:
# example of Python list subtraction
a - b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [60]:
a_np - b_np

array([-3, -3, -3])

In [62]:
# python lists have no conception of mulitiplication
a * b

TypeError: can't multiply sequence by non-int of type 'list'

In [63]:
# numpy knows what matrix multiplication
a_np * b_np

array([ 4, 10, 18])

In [66]:
# python lists multiplication will replicate itself (or * n itself)
## Only works with a scalar/ int.  Will break with a float
a * 3

TypeError: can't multiply sequence by non-int of type 'float'

In [69]:
# numpy understand matrix multiplication with a scalar and float!
a_np * 3.5

array([ 3.5,  7. , 10.5])

In [70]:
a_np ** b_np

array([  1,  32, 729])

In [71]:
a_np / 2

array([0.5, 1. , 1.5])

In [72]:
a_np / b_np

array([0.25, 0.4 , 0.5 ])

In [73]:
a_np % b_np

array([1, 2, 3])

## Negative Indexing

1. Negative indexing is hard to get right in complicated situations
2. I (AMY) personally use it only:
    - I need that backwards behavior while iterating through the array.
    - I want the last element of an array when you don't know the size of the array.

In [81]:
# creating array from a list

# input into array function: list
## documentation on numpy.array: https://numpy.org/doc/stable/reference/generated/numpy.array.html
a_array = np.array(a)
b_array = np.array(b)

print(a_array)

[1 2 3]


In [82]:
# negative indexing in 1 dimension
# print 3
a_array[-1]

3

In [83]:
twod = np.array([ (1,2,3), (4,5,6) ], dtype = float)

print(twod)

# how to get array dimensions
print("Array dim: ", twod.shape)

# how to get total number of elements in array
print("Array size: ", twod.size)

[[1. 2. 3.]
 [4. 5. 6.]]
Array dim:  (2, 3)
Array size:  6


In [85]:
# how to get a single element in a 2D Array
#   -3 -2 -1
# -2 1  2  3
# -1 4  5  6

# Get 6
## Syntax: array_identifier[row_index, col_index]
print(twod[-1, -1])

## Syntax: array_identifier[row_index][col_index]
print(twod[1][2])

6.0
6.0


In [86]:
twod = np.array([ (1,2,3), (4,5,6), (7,8,9) ], dtype = float)

print(twod)

print("Array dim: ", twod.shape)
print("Array size: ", twod.size)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Array dim:  (3, 3)
Array size:  9


In [93]:
# Trying to get 8

## SO HARD!
twod[0][-2]

2.0

In [ ]:
# how to get a row
## syntax : array_identifier[row_index]
threed[1]

![](https://i.stack.imgur.com/NWTQH.png)

In [94]:
# 3 D array
three_d_array = [
    [
        [1, 2], [3, 4]
    ], 
    [
        [5, 6], [7, 8]
    ]
]

three_d = np.array(three_d_array)

In [95]:
three_d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [96]:
three_d.shape

(2, 2, 2)

In [79]:
# getting 2 with normal indexing
print(three_d[0][0][1])
print(three_d[0, 0, 1])

2
2


In [99]:
# getting the last element with negative indexing
three_d[-1, -2, -2]

5

# Slicing
1. Slice is any subsection of the array or list

In [100]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# access slice with syntax : my_list[start_index: end_index + 1:(optional) increment value]

# let's get 4-> 7 as a slice
my_list[3:7]

[4, 5, 6, 7]

In [106]:
# skipping every other
my_list[3:7:2]

[4, 6]

In [102]:
my_array = np.array(my_list)

my_array[3: 7]

array([4, 5, 6, 7])

In [101]:
# syntax for subsection that starts at index 0:

# option1 : my_list[0: end_index + 1]
# get 1 -> 3
print(my_list[0: 3])

# option 2: my_list[: end_index + 1]

print(my_list[: 3])

    

[1, 2, 3]
[1, 2, 3]


In [103]:
# same behavior in numpy
my_array[:3]

array([1, 2, 3])

In [107]:
# negative indexing with slices 

# 10, 9, 8
## I have to specify a negative step to get the slice backwards
my_list[-1:-4:-1]

[10, 9, 8]

In [108]:
# Get the whole array backwards
my_list[::-1]

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [109]:
my_array[-1:-4:-1]

array([10,  9,  8])

## Creating custom arrays using Numpy with increasing range

- np.arange(`Start`, `Stop`, `Step`)

In [110]:
np.arange(1, 5, 1)

array([1, 2, 3, 4])

In [112]:
# can take floats at any value
np.arange(1.2, 5, 1.5)

array([1.2, 2.7, 4.2])

In [113]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [114]:
# when there are logical errors in the parameters, you get an empty array
np.arange(-1, 5, -0.75)

array([], dtype=float64)

In [ ]:
Z = np.array([[11, 22, 33, 44, 55], 

## Creating a custom array using the Gaussian Distribution

- np.linspace(`Start`, `Stop`, `No of Values`)

In [ ]:
np.linspace(1, 5, 20)

**np.linspace()** is better for fractional values as it utilises the `Gaussian Distribution` for generating the values of the array

## Creating an array of Random Values

- np.random.rand(`shape`)

- This creates an array of the given shape using random values between 0 and 1 from a **`uniform distribution`**.

In [ ]:
np.random.rand(4, 5)

- np.random.randn(`shape`)

- This creates an array of the given shape using random values which follow the **`Gaussian Normal Distribution`**

In [ ]:
np.random.randn(4, 5)

## Visualising the Distributions for the functions

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
plt.hist(np.random.rand(100000), bins=100, density=True, histtype="step", label="Rand")
plt.hist(np.random.randn(100000), bins=100, density=True, histtype="step", label="Randn")
plt.axis([-2.5, 2.5, 0, 1.1])
plt.legend(loc = "upper left")
plt.title("Random distributions")
plt.xlabel("Value")
plt.ylabel("Density")
plt.show()

## Creating an array using a custom function

- np.fromfunction(`Function Name`, `Shape`)

- This creates an array of the required shape after `mapping the numbers to the function`.

- It is very efficient as it refers to the `function header only once`.

In [ ]:
def polynomial(x, y, z):
    return x + 10 * y + 100 * z

np.fromfunction(polynomial, (3, 5, 2))

## Reshaping Numpy Arrays

- `nd Array Object`.shape = (`New Shape`)

In [ ]:
new = np.random.rand(12)
print(new)
print(new.shape)

In [ ]:
print("Reshaping the Array to (12, 1), (3, 4) and (6, 2)")

new.shape = (12, 1)
print("\n(12, 1)\n", new)

new.shape = (3, 4)
print("\n(3, 4)\n", new)

new.shape = (6, 2)
print("\n(6, 2)\n", new)

- `nD Array Object`.reshape(`Shape`)

In [ ]:
new = new.reshape(4, 3)
print("\n(4, 3)\n", new)

new = new.reshape(2, 6)
print("\n(2, 6)\n", new)

## Arithematic Operations

- All the arithematic operations on arrays work `element-wise` unless invoked using vectorization.

In [ ]:
# Declaring the Arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

print("A: ", a)
print("B: ", b)

In [ ]:
print("Performing Arithematic Operations on the Arrays: ")
print(f"\nA + B: {a + b}\n")
print(f"\nA - B: {a - b}\n")
print(f"\nA * B: {a * b}\n")
print(f"\nA / B: {a / b}\n")
print(f"\nA // B: {a // b}\n")
print(f"\nA ** B: {a ** b}\n")
print(f"\nA % B: {a % b}\n")

## Numpy Broadcasting

- Numpy broadcasting is applied when an arithematic operation is performed on arrays but their shape dont match

- **Thus numpy automatically extends / broadcasts the array to match a shape in certain cases**

In [ ]:
a = np.arange(5).reshape(1, 5)
print(a)
print(a.shape)

## Rule - 1

- **On trying to `sum with a rank - 1 vector` numpy automatically broadcasts the vector**

In [ ]:
a + [6, 7, 8, 9, 10]

- Thus numpy has automatically converted
- [6, 7, 8, 9, 10] to [[6, 7, 8, 9, 10]]

## Rule - 2

- **On trying to a `sum with a column vector` numpy automatically broadcasts the vector**

In [ ]:
a = np.arange(6).reshape(2, 3)
print(a)
print(a.shape)

In [ ]:
a + [[100], [200]]

- Thus numpy automatically converted the array
- [[100, 100, 100], [200, 200, 200]]

## Combining Rule 1 and Rule 2

In [ ]:
print(a)
print(a.shape)

In [ ]:
a + [100, 200, 300]

- Thus numpy automatically converts the array
- [[100, 200, 300],  
   [100, 200, 300]]

## Numpy Broadcasting with Conditionals

- Numpy broadcasting can also be applied to conditionally select the elements of the array.

- On apply a conditional it works `element-wise to give a boolean array`.

In [ ]:
a = np.arange(5)
b = np.arange(6, 11)
print(a)
print(b)

In [ ]:
print("Checking which values of A < B: ")
print(a < b)

In [ ]:
a = a + 10 + np.random.randn(5)
b = b + np.random.rand(5)
print(a)
print(b)
print("Checking which values of A < B: ")
print(a < b)

## Conditional Selection

- Numpy arrays on conditional selection `return a slice of the array` which match the condition

In [ ]:
print(f"b[b > 7]: {b[b > 7]}")

## Math and Statistical methods using Numpy

In [ ]:
a = np.linspace(1, 10, 6).reshape(2, 3)
print(a)

In [ ]:
for func in (a.mean, a.min, a.max, a.sum, a.prod, a.std, a.var):
    print(func.__name__, " = ", func())

- Thus all the major math and statistical functions are standard methods of the `Numpy nd - array object` which  
can be referenced using the `. operator`.

- The standard functions also provide an optional parameter `Axis` which changes the way the methods are applied to the array:
    - Column Wise: `Axis = 0`
    
    - Row Wise: `Axis = 1`

- `Axis = 0`: **[1 + 6.4 , 2.8 + 8.2 , 4.6 + 10]**

- Column - Wise Addition

In [ ]:
print(f"Column Wise Addition: \n{a.sum(axis=0)}")

- `Axis = 1`: **[1 + 2.8 + 4.6 , 6.4 + 8.2 + 10]**

- Row - Wise Addtion

In [ ]:
print(f"Row Wise Addition: \n{a.sum(axis=1)}")

## Numpy Universal Functions

- Numpy universal functions work using a vectorised wrapper to perform operations on arrays.

- They are very fast as they split the calculations over multiple cores of CPU

- They are of two types:
    - Fast Element-Wise `unary operations`
        - abs, sqrt, exp, log, ceil ...
    
    - Fast Element-Wise `binary operations`
        - dot, cross, greater, maximum ...

In [ ]:
a = np.linspace(1, 5, 10)
print(a)

## Unary Operations

In [ ]:
print("Unary Operations")
for func in (np.abs, np.sqrt, np.square, np.exp, np.log, np.ceil):
    print("\n", func.__name__)
    print(func(a))

In [ ]:
b = np.random.rand(10)
print(b)

## Binary Operations

In [ ]:
print("Binary Operations")
print("\nDot: ", np.dot(a, b))
print("\nGreater: ", np.greater(a, b))
print("\nMaximum: ", np.maximum(a, b))

## Indexing in Numpy Arrays

- `One Dimensional Arrays` follow the same indexing as python lists  

    [`Start`:`Stop`:`Step`]

In [ ]:
print(a)

In [ ]:
print(a[1:-3])

In [ ]:
print(a[2::2])

In [ ]:
print(a[::-1])

- `Multi Dimensional Arrays` follow interior indexing at each level

   [`First Dimesion <Start, Stop, Step>`, `Second Dimension <Start, Stop, Step>`, ....]

In [ ]:
multi = np.random.rand(3, 4)
print("\n2D Array: \n", multi)

In [ ]:
print(f"Accessing the 1st Row: {multi[1, :]}")

In [ ]:
print(f"Accessing the 1st Column: {multi[:, 0]}")

In [ ]:
print("Accessing a subset of the array: \n", multi[1:, 1:-1])

In [ ]:
print(f"Accessing only the first 2 x 2 of the array:\n {multi[:-1, :-2]}")

## Iterating over the Array

In [ ]:
for row in multi:
    print(row)

In [ ]:
for row in multi:
    for col in row:
        print(col)

- To convert a multi-dimensional array into a 1D array for iteration without unpacking using a for loop use the  
`<array object>.flat` attribute

In [ ]:
for i in multi.flat:
    print(i)

## Stacking Numpy Arrays

- Numpy provides various methods to stack arrays together
    - hstack
    - vstack
    - concatenate
    - stack
    
- Each function takes `tuple of array objects` as a parameter and returns the new stacked array

In [ ]:
a = np.arange(1, 9).reshape(2, 4)
b = np.arange(-1, -9, -1).reshape(2, 4)
print(a)
print(b)

## Using HStack and VStack:

- np.hstack(`Tuple of Array Objects`)

- np.vstack(`Tuple of Array Objects`)

In [ ]:
print("Here is the Horizontal Stack: \n", np.hstack((a, b)))
print("\nHere is the Vertical Stack: \n", np.vstack((a, b)))

## Concatenate:

- The concatenate method generalises both the operations performed by the hstack and vstack methods.

- The concatenate method takes an additional argument `Axis` to provide choice of stack operation.

- np.concatenate(`Tuple of Array Objects`, `Axis`)

In [ ]:
print("Here is the Horizontal Stack using np.stack(axis = 1): \n", np.concatenate((a, b), axis=1))
print("\nHere is the Vertical Stack using np.stack(axis = 0): \n", np.concatenate((a, b), axis=0))

## Stack:

- The stack method takes a tuple of array objects and adds each of them to a seperate dimension.

- np.stack((`Tuple of Array Objects`))

In [ ]:
np.stack((a, b))

## Splitting Numpy Arrays:

- Splitting the Numpy arrays follows the same rules as the stack()

- vsplit(`Array`, `No of Parts`), hsplit(`Array`, `No of Parts`), split(`Array`, `No of Parts`)

- Each of the split() expects a set of variables to unpack the returned values.

**The split() takes an additional parameter axis to generalise the to both the cases**

In [ ]:
hstack = np.concatenate((a, b), axis=1)
vstack = np.concatenate((a, b), axis=0)
print("Horizontal Stack\n", hstack)
print("Vertical Stack\n", vstack)

In [ ]:
print("Splitting the hstack into 4 columns: ")
c1, c2, c3, c4 = np.hsplit(hstack, 4)
print("\nC1:\n ", c1)
print("\nC2:\n ", c2)
print("\nC3:\n ", c3)
print("\nC4:\n ", c4)

In [ ]:
print("Splitting the vstack into 2 matrices: ")
m1, m2 = np.vsplit(vstack, 2)
print("\nM1:\n ", m1)
print("\nM2:\n ", m2)

In [ ]:
print("Using the split function to generalise to both the cases: ")
print(np.split(hstack, indices_or_sections=4, axis=1))
print(np.split(vstack, indices_or_sections=2, axis=0))

## Linear Algebra

## Matrix Transpose:

- Matrix Transpose can be done in three ways:

    - np.transpose(`Array Object`)
    
    - `Array Object`.transpose()
    
    - `Array Object`.T
    
    **Here `.T` is short for `.transpose()`**
    
    **`.T` works only on arrays rank >= 2. Thus it is ineffective against `1D arrays`**

In [ ]:
print(a)

In [ ]:
print("Transpose of A: \n", a.T)

In [ ]:
print(b)

In [ ]:
print("Transpose of B: \n", b.transpose())

In [ ]:
oneD = np.linspace(1, 5, 10)
print(oneD)

In [ ]:
print(oneD.T)

In [ ]:
print(oneD.reshape(1, 10).T)

## Identity Matrix:

- np.eye(`Order`)

- Creates and returns an identity matrix of the given order

In [ ]:
np.eye(3)

## Matrix Multiplication

- Matrix multiplication of two arrays is performed using two reference methods

    - `Array - 1`.dot(`Array - 2`)
    
    - np.dot(`Array - 1`, `Array - 2`)
    
- **On performing multiplication using `*` element wise product is calculated**

In [ ]:
print(a)
print(b)

In [ ]:
print(np.dot(a, b.T))

In [ ]:
print(b.dot(a.T))

In [ ]:
print(a * b)

## Most of the common Linear Algebra operations require invoking the `numpy.linalg` module

## Matrix Inverse

- np.linalg.inv(`Array`)

- This calculates the inverse of a square matrix

In [ ]:
a = np.random.rand(5, 5)
print(a)

In [ ]:
print("The inverse of A is: \n")
print(np.linalg.inv(a))

## Matrix Determinant

- np.linalg.det(`Array`)

In [ ]:
print("The determinant of A is: ")
print(np.linalg.det(a))

## Eigen Values and Eigen Vectors

- `Eigen Values`, `Eigen Vectors` = np.linalg.eig(`Array`)

- This returns two arrays which are unpacked to store the eigen values and the eigen vectors

In [ ]:
b = np.arange(9).reshape(3, 3)
print(b)

In [ ]:
eigen_values, eigen_vectors = np.linalg.eig(b)
print("The Eigen Values are:\n ")
print(eigen_values)
print("\nThe Eigen Vectors are:\n ")
print(eigen_vectors)

## Diagonal And Trace

- The diagonal and trace of a matrix can be called from the numpy reference

- np.diag(`Array`)

- np.trace(`Array`)

In [ ]:
print("The Diagonal of B is:\n", np.diag(b))
print("\nThe Trace of B is:\n", np.trace(b))

## Saving and Loading Arrays

- Binary Format `.npy`

- Text Format `.csv`

## Binary Format:

- **Saving the Array:** np.save(`File.npy`, `Array`)

- **Loading the Array:** np.load(`File.npy`)

In [ ]:
print("Saving the array to a binary file")
np.save("Eval", eigen_values)

In [ ]:
with open("Eval.npy", "rb") as file:
    array = file.read()
    
print("Reading the Binary File:\n ", array)

In [ ]:
print("Loading the Array: \n")
array = np.load("Eval.npy")
print(array)

## Text Format:

- **Saving the Array:** np.savetxt(`File.csv`, `Array`, `Delimiter`)

- **Loading the Array:** np.loadtext(`File.npy`, `Delimiter`)

In [ ]:
print("Saving the array to a CSV")
np.savetxt("Evect.csv", eigen_vectors, delimiter=",")

In [ ]:
with open("Evect.csv") as file:
    array = file.read()
    
print(array)

In [ ]:
print("Loading the Array: \n")
array = np.loadtxt("Evect.csv", delimiter=",")
print(array)